-- 101:

-- 7. "Profiles" jadvalini yaratamiz
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users(id) PRIMARY KEY,
  full_name text,
  avatar_url text,
  email text,
  role text DEFAULT 'user',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Trigger for new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email,
    CASE WHEN new.email = 'admin@shopvex.com' THEN 'admin' ELSE 'user' END);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
-- 1. Avval mavjud jadvallarni tozalaymiz (agar bor bo'lsa)
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;

-- 2. "Categories" jadvalini yaratamiz
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  icon text,
  color text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. "Products" jadvalini yaratamiz
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  price text,
  location text,
  image_url text,
  description text,
  seller_name text,
  seller_joined text,
  category_id bigint REFERENCES categories(id),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Kategoriyalarni qo'shamiz (Uzbek tilida)
INSERT INTO categories (name, icon, color) VALUES
('Telefonlar', '📱', '#ffce32'),
('Transport', '🚗', '#23e5db'),
('Ko''chmas mulk', '🏠', '#3a77ff'),
('Uy jihozlari', '🛋️', '#ff5636'),
('Elektronika', '💻', '#CED1D3'),
('Velosipedlar', '🏍️', '#002f34'),
('Ish o''rinlari', '💼', '#3a9b6d'),
('Xizmatlar', '🛠️', '#ffce32'),
('Boshqa', '📦', '#999999');

-- 5. Boshlang'ich mahsulotlarni qo'shamiz
INSERT INTO products (title, price, location, category_id, image_url, description, seller_name, seller_joined) VALUES
('iPhone 13 Pro Max - 256GB', '950$', 'Toshkent', 1, 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&w=600&q=80', 'Holati ideal, batareya 95%. Karobka va kabeli bor.', 'John Doe', '2021'),
('2020 Honda Civic Turbo', '22,500$', 'Samarqand', 2, 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80', 'Yurgani kam, bir qo''l haydalgan. Servisda qarab turilgan.', 'Car Traders', '2019'),
('Hashamatli kvartira ijaraga', '2,200$/oyiga', 'Buxoro', 3, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80', '2 xona, ko''l manzarasi bilan. Sport zal va basseyn bor.', 'Real Estate Pros', '2020'),
('Gaming PC RTX 3080', '1,800$', 'Navoiy', 5, 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=600&q=80', 'Kuchli o''yin kompyuteri. 4k o''yinlarni bemalol o''ynaydi.', 'GamerGuy', '2023'),
('Sony A7III Camera', '1,400$', 'Andijon', 5, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80', 'Faqat body. Probeg < 10k. Yangidek.', 'PhotoStudio', '2022');

-- 6. Hamma ma'lumotlarni o'qishga ruxsat berish (Public Access)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Add user_id to products
ALTER TABLE products ADD COLUMN IF NOT EXISTS user_id uuid DEFAULT auth.uid();

-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid REFERENCES auth.users(id) NOT NULL,
  receiver_id uuid REFERENCES auth.users(id) NOT NULL,
  sender_name text,
  receiver_name text,
  product_id bigint REFERENCES products(id),
  message_text text NOT NULL,
  date text DEFAULT timezone('utc'::text, now())::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- +++ YANGI: Buyurtmalar (Orders) jadvali +++
CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL, -- Buyurtma bergan shaxs
  product_id bigint REFERENCES products(id) NOT NULL,
  payment_method text NOT NULL, -- 'karta' yoki 'naqd'
  card_number text, -- faqat karta bo'lsa
  phone text NOT NULL,
  address text NOT NULL,
  quantity int DEFAULT 1,
  status text DEFAULT 'kutilmoqda',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages" ON messages 
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can insert messages" ON messages 
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Users can view their own orders" ON orders 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert orders" ON orders 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public read products" ON products FOR SELECT USING (true);
CREATE POLICY "Public insert products" ON products FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Public read categories" ON categories FOR SELECT USING (true);
